[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cell-viewer"
version = "0.1.0"
description = "A PySide6-based TIFF stack viewer"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
dependencies = [
    "PySide6>=6.6.0",
    "numpy>=1.24.0",
    "scikit-image>=0.22.0",
    "matplotlib>=3.8.0",
]

[project.scripts]
cell-viewer = "cell_viewer.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/cell_viewer"]

[tool.hatch.metadata]
allow-direct-references = true 